name: Build artifacts to link to release

on:
  push:
    tags:
      - '*'

jobs:
  build-linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '12'
      - name: Build and publish artifact
        run: npx electron-builder -p always
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  build-windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '12'
      - name: Build and publish artifact
        run: npx electron-builder -p always
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and publish portable artifact
        run: npx electron-builder --win portable -p always
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  build-mac:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
         node-version: '12'
      - name: Build and publish artifact
        run: npx electron-builder -p always
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
