name: CI
on:
  push:
    paths-ignore:
      - '**/.github/**'
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '12'
      - name: Install npm modules
        run: npm install
      - name: Run ESLint
        run: npm run lint
  unit-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '12'
      - name: Install npm modules
        run: npm install
      - name: Run Jest
        run: npm run test
